# Generated by Django 2.0.4 on 2018-11-06 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('site', models.URLField()),
                ('fundacao', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='EstiloMusical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Musico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('idade', models.DecimalField(decimal_places=0, max_digits=20)),
                ('banda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Banda')),
            ],
        ),
        migrations.AddField(
            model_name='estilomusical',
            name='musico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.Musico'),
        ),
        migrations.AddField(
            model_name='banda',
            name='estilo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.EstiloMusical'),
        ),
    ]
