# Generated by Django 2.0.4 on 2018-11-06 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estilomusical',
            name='musico',
        ),
        migrations.RemoveField(
            model_name='musico',
            name='banda',
        ),
        migrations.AddField(
            model_name='musico',
            name='bandas',
            field=models.ManyToManyField(to='music.Banda'),
        ),
    ]
